language: cpp

os:
  - osx

compiler:
    - g++
    - clang

before_install:
    brew install sdl2

script:
    - mkdir build
    - cd build
    - cmake -DBUILD_TESTS=ON ..
    - cmake --build .
    - ctest -vv
