# SYNOPSIS:
#
#   make [all]  - makes everything.
#   make TARGET - makes the given target.
#   make clean  - removes all files generated by make.

# Points to the root of Google Test, relative to where this file is.
# Tweak this based on where google test is installed
GTEST_DIR = ../googletest/googletest

USER_DIR = .

CPPFLAGS += -isystem $(GTEST_DIR)/include

CXXFLAGS += -g -Wall -Wextra -pthread

TESTS = sample1_unittest

GTEST_HEADERS = $(GTEST_DIR)/include/gtest/*.h \
                $(GTEST_DIR)/include/gtest/internal/*.h

src = $(wildcard src/*.cpp)
lib = $(wildcard src/lib/*.h)
obj = $(src:.cpp=.o)

FRAMEWORK = -framework sdl2

thiessen : $(obj) $(lib)
	$(CXX) -o $@ $(obj) $(CXXFLAGS) $(FRAMEWORK)

r:
	make && ./thiessen in/small.in

tests : $(TESTS)

.PHONY: clean
clean :
	rm -f $(TESTS) tests/gtest.a tests/gtest_main.a *.o

GTEST_SRCS_ = $(GTEST_DIR)/src/*.cc $(GTEST_DIR)/src/*.h $(GTEST_HEADERS)

gtest-all.o : $(GTEST_SRCS_)
	$(CXX) $(CPPFLAGS) -I$(GTEST_DIR) $(CXXFLAGS) -c \
            $(GTEST_DIR)/src/gtest-all.cc

gtest_main.o : $(GTEST_SRCS_)
	$(CXX) $(CPPFLAGS) -I$(GTEST_DIR) $(CXXFLAGS) -c \
            $(GTEST_DIR)/src/gtest_main.cc

gtest.a : gtest-all.o
	$(AR) $(ARFLAGS) $@ $^

gtest_main.a : gtest-all.o gtest_main.o
	$(AR) $(ARFLAGS) $@ $^

sample1_unittest.o : sample1_unittest.cc \
                     ../src/lib/voronoi.h \
					 $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c sample1_unittest.cc

sample1_unittest : sample1_unittest.o gtest_main.a ../src/circle.o ../src/dcel.o ../src/graphics.o ../src/line.o ../src/point.o ../src/voronoi.o
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -lpthread $^ -o $@
